### PR TITLE
Value of delayAfterRunSeconds is not shown on the final submit panel

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

https://github.com/stolostron/backlog/issues/24697

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
The bug also occurs on all other ACM UI page which is using the number input, like `amazon-hypershift` and `placement`, etc

Before 
Screen Shot 2022-08-04 at 11 57 04 PM
Screen Shot 2022-08-05 at 12 00 50 AM
Screen Shot 2022-08-05 at 12 00 50 AM

**Comment by ChunxiAlexLuo** [comment]
After
Screen Shot 2022-08-05 at 12 02 39 AM
-a67eea84f83d
Screen Shot 2022-08-05 at 12 04 10 AM
.png">

**Comment by ChunxiAlexLuo** [comment]
@drkho For the wrapping issue, it seems current all console UI is using the wrap, please check the items on the other submission page like `amazon-hypershift` and `placement`, etc.  So I decide to don't change it to `nowrap`, if you disagree with this, please discuss it with @jamestalton and @KevinFCormier.

**Review by jamestalton — APPROVED** [review]
lgtm

**Comment by drkho** [comment]
The field was displayed as a single word - `delayRunAfterSeconds`, that's why i made it part of the issue. However, changing it to multiple words also works. The wrapping then makes sense to me. Thanks. @ChunxiAlexLuo .

**Pull request merged**
