### PR TITLE
prop modifications

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

### CODE REVIEW

**Comment by Randy424** [comment]
/cc hold
(WIP)

**Comment by chenz4027** [comment]
@Randy424 You may want ot update the params in ApplicationExample.tsx as well

**Comment by Randy424** [comment]
@chenz4027 Sorry for the wait, I merged with master, and favored your prop setup, so my additions are limited to the helmChannel prop.

**Review by chenz4027 — APPROVED** [review]
lgtm

**Pull request merged**
