### PR TITLE
Allow defaultRender

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>
image

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@chenz4027 Can you explain the purpose of this? From looking over the code, I'm wondering if `disallowEmpty` might better convey what this new prop is supposed to do.

**Comment by chenz4027** [comment]
@KevinFCormier It's for displaying the children of WizArrayInput by default. The change will not be in the placement, but will happen in multiple sources as per https://github.com/stolostron/console/pull/2911
The change will mimic what app sub does where
1. It will render tiles for helm and git
2. The user will have options to add more repositories if they want

Let me take a look at the disallowEmpty

**Review by KevinFCormier — APPROVED** [review]

**Comment by chenz4027** [comment]
🫳🏾💨🪃 @Randy424 
I had no idea how you did the emoji, just copy pasted it haha

**Review by Randy424 — APPROVED** [review]
/lgtm

**Pull request merged**
